CREATE DATABASE IF NOT EXISTS portsDB;
USE portsDB;

CREATE TABLE IF NOT EXISTS users
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userName VARCHAR(255) NOT NULL,
	pass VARCHAR(255) NOT NULL,
	conections INT DEFAULT 0
);